package ee.ttu.luncher

import org.kie.api.runtime.KieRuntime
import ee.ttu.luncher.drools.FactVo
 
rule "Vegeterian menu"
    // dialect "mvel"
    when
        fact : FactVo ( vegan == true )
    then
        retract(fact)
        //System.out.println( fact );
        
end

rule "Reservation allowed"
    when
        fact : FactVo ( reservation == true )
    then
        //retract(fact)        
        //System.out.println( fact );
        
end

rule "Life, universe and everything!"
    when
        fact : FactVo (  )
    then
        System.out.println( fact );
end
